# -*- coding: utf-8 -*-
"""feature-extraction-Ngrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIG-o6VT5EuSELcmLNI8d6BGKpG1M1wf
"""

import numpy as np
import pandas as pd

df = pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output':[1,1,0,0]})

df

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1, 3))

bow = cv.fit_transform(df['text'])

# vocab
print(cv.vocabulary_)

print(bow[0].toarray())
print(bow[1].toarray())

cv.transform(["campusx watch and write comment of campusx"]).toarray()

cv.transform(["people watch and write comment of campusx"]).toarray()