# -*- coding: utf-8 -*-
"""feature-extraction-TFIDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIG-o6VT5EuSELcmLNI8d6BGKpG1M1wf
"""

import numpy as np
import pandas as pd

df = pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output':[1,1,0,0]})

df

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

print(tfidf.idf_)
print(tfidf.get_feature_names_out())