# -*- coding: utf-8 -*-
"""game-of-thrones-word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vO9FmK8RDKCOdglRMzl2O9Aoa-9hqoRS
"""

import numpy as np
import pandas as pd

!pip install gensim

import gensim
import os

import nltk
nltk.download('punkt_tab')

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
data_dir = '/content/drive/MyDrive/GOT_DATA'
for filename in os.listdir(data_dir):

    with open(os.path.join(data_dir,filename), 'r', encoding='latin-1') as f:
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

len(story)

model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    workers = 4,
)

model.build_vocab(story)

model.train(story, total_examples=model.corpus_count, epochs= model.epochs)

model.wv.most_similar('daenerys')

model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

model.wv.doesnt_match(['cersei','jemmy','robb','tyrion'])

model.wv['jon']

model.wv.similarity('arya','sansa')

model.wv.similarity('cersei','sansa')

model.wv.similarity('cersei','jon')

model.wv.get_normed_vectors()

y = model.wv.index_to_key

len(y)

from sklearn.decomposition import PCA

pca = PCA(n_components = 3)

x = pca.fit_transform(model.wv.get_normed_vectors())

x.shape

import plotly.express as px
fig = px.scatter_3d(x[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()