# -*- coding: utf-8 -*-
"""Vikings_Word2Vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gly4BE5W2HAS1piSad_biQw2N_F9f22n
"""

import numpy as np
import pandas as pd

!pip install gensim

import gensim
import os

import nltk
nltk.download('punkt_tab')

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
data_dir = '/content/drive/MyDrive/Vikings_dataset'
for filename in os.listdir(data_dir):

    with open(os.path.join(data_dir,filename), 'r', encoding='latin-1') as f:
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

len(story)

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

def remove_stopwords(text):
  new_text = []

  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return " ".join(x)

model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    workers = 4,
)

model.build_vocab(story)

model.train(story, total_examples=model.corpus_count, epochs= model.epochs)

model.wv.most_similar('lagertha')

model.wv.doesnt_match(['floki','bjorn','lagertha','ubbe','rollo','ragnar'])

model.wv.doesnt_match(['rollo','siggy','ivar','gisla'])

model.wv['torvi']

model.wv.similarity('floki','freydis')

model.wv.similarity('floki','athelstan')

model.wv.similarity('athelstan','ivar')

model.wv.get_normed_vectors()

y = model.wv.index_to_key

len(y)

from sklearn.decomposition import PCA

pca = PCA(n_components = 3)

x = pca.fit_transform(model.wv.get_normed_vectors())

x.shape

import plotly.express as px
fig = px.scatter_3d(x[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()