# -*- coding: utf-8 -*-
"""Word2Vec_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/word2vec-demo-03ca1196-d7eb-4d6b-9388-9ede09962424.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250209/auto/storage/goog4_request%26X-Goog-Date%3D20250209T042457Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D74a21e8bd7d4de71916ad92e53b6a93cccd055eaa25c8ed688d48acd3605cd915efb76a426eaeb60167893607c894a63cb83fb296738ef9d54a9feb334ec3cd2d2b5001975f7d2ac8d3dcafc6817b4bcd765a40a1ca9d74b3e0557ed4a845706c41bdc94834064fc7daaf8ada9cf69f3bb5117a9168c0a94d388f50fb1176d22de73afe9cc3025433a3b99471d516971a8f1b0bb3e1e1325c696cc6463fd8ec333633f335fb6e70b0ef0d0cb787dcce37cbeb5d438e7815599895d2f2a5d1384460ff2c73c3ec9753aa2bf012829dec0d1c9b38a582a845f28042fedb88be00f48a09f2f1e1f962e3a73e7c3a949c06b23e0bba3bf87bfd9a5ef62265724972c
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
leadbest_googlenewsvectorsnegative300_path = kagglehub.dataset_download('leadbest/googlenewsvectorsnegative300')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import gensim
from gensim.models import Word2Vec,KeyedVectors

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # path to dataset
# word2vec_path = "/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin"
# 
# # Load 500,000 most common words
# model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_path, binary = True, limit = 500000)

model['cricket']

model.most_similar('man')

model.most_similar('cricket')

model.most_similar('facebook')

model.similarity('man','woman')

model.similarity('man','PHP')

model.doesnt_match(['PHP','java','monkey'])

vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

vec = model['INR'] - model ['India'] + model['England']
model.most_similar([vec])